from pydantic import BaseModel, Field
from typing import Optional, List


class SearchRequest(BaseModel):
    query: str = Field(..., min_length=1, max_length=1000, description="Natural language search query")
    meeting_ids: List[int] = Field(default_factory=list, description="List of meeting IDs authorized for the user")
    top_k: int = Field(default=5, ge=1, le=20, description="Maximum number of relevant chunks to retrieve")


class SearchReference(BaseModel):
    meeting_id: Optional[int] = Field(default=None, description="ID of the referenced meeting")
    transcript_id: Optional[int] = Field(default=None, description="ID of the referenced transcript")
    chunk_index: Optional[int] = Field(default=None, description="Index of the referenced chunk")
    start_time: Optional[float] = Field(default=None, description="Start timestamp in seconds")
    end_time: Optional[float] = Field(default=None, description="End timestamp in seconds")


class SearchResponse(BaseModel):
    answer: str = Field(..., description="Grounded RAG answer generated by LLM")
    references: List[SearchReference] = Field(default_factory=list, description="References for retrieved context")
    retrieved_chunks: Optional[List[dict]] = Field(default=None, description="Optional debug info for retrieved chunks")
